run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - gofmt
    - goimports
    - gocyclo

issues:
  exclude-use-default: false
